application: amazon-competitor-analisys

version: 1

runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css/(.*\.(css))
  static_files: static/css/app.css
  upload: static/(.*\.(css))

- url: /script/(.*\.(js))
  static_files: static/script/bundle.js
  upload: static/(.*\.(js))
  
- url: .*
  script: main.app


builtins:
- deferred: on

  
libraries:
- name: lxml
  version: "2.3"
- name: jinja2                                                                  
  version: latest
  